import sys
import os
import subprocess
import platform

# Handle TOML parsing depending on Python version
try:
    import tomllib
except ImportError:
    try:
        import tomli as tomllib
    except ImportError:
        print("Error: tomli library not found. Run pip install tomli.", file=sys.stderr)
        sys.exit(1)

def run_command(cmd, cwd=None):
    """Executes a shell command and yields output."""
    print(f"Running: {cmd}")
    try:
        proc = subprocess.run(
            cmd, 
            cwd=cwd, 
            shell=True, 
            check=True,
            text=True,
            capture_output=True
        )
        print(proc.stdout)
        return True
    except subprocess.CalledProcessError as e:
        print(f"Command failed with exit code {e.returncode}", file=sys.stderr)
        print(e.stderr, file=sys.stderr)
        return False

def main():
    if len(sys.argv) < 2:
        print("Usage: python toml_processor.py <path_to_toml>")
        sys.exit(1)

    toml_path = sys.argv[1]
    
    if not os.path.exists(toml_path):
        print(f"Error: File {toml_path} not found.")
        sys.exit(1)

    try:
        with open(toml_path, "rb") as f:
            config = tomllib.load(f)
    except Exception as e:
        print(f"Error parsing TOML file: {e}", file=sys.stderr)
        sys.exit(1)

    orchestration = config.get("orchestration", {})
    ticket = orchestration.get("ticket", "UNKNOWN")
    purpose = orchestration.get("purpose", "")
    documentation = config.get("documentation", {})
    bdd = documentation.get("bdd", "")
    repositories = config.get("repository", [])
    
    print(f"=== Starting Orchestration for Ticket: {ticket} ===")
    if purpose:
        print(f"Purpose:\n{purpose.strip()}\n")
    
    # Base workspace directory 
    workspace_dir = os.path.join(os.path.expanduser("~"), "Documents", "ForgeFlowWorkspaces", ticket)
    os.makedirs(workspace_dir, exist_ok=True)
    
    for repo in repositories:
        name = repo.get("name")
        print(f"\n--- Processing Repository: {name} ---")
        
        repo_dir = os.path.join(workspace_dir, name)
        
        # Clone Command
        clone_cmd = repo.get("clone_cmd")
        if clone_cmd and not os.path.exists(repo_dir):
            if not run_command(clone_cmd, cwd=workspace_dir):
                print(f"Failed to clone {name}. Skipping.", file=sys.stderr)
                continue
                
        # Checkout Branch
        branch_cmd = repo.get("branch_cmd")
        if branch_cmd and os.path.exists(repo_dir):
            run_command(branch_cmd, cwd=repo_dir)
            
        # Build Commands
        build_cmds = repo.get("build_cmds", [])
        for cmd in build_cmds:
            run_command(cmd, cwd=repo_dir)
            
        # Environment Template
        if repo.get("env_template"):
            env_path = os.path.join(repo_dir, ".env")
            if not os.path.exists(env_path):
                print(f"Creating .env template at {env_path}")
                with open(env_path, "w") as f:
                    f.write(f"# Auto-generated by ForgeFlow for {ticket}\n")
                    
    # Write BDD
    if bdd:
        bdd_path = os.path.join(workspace_dir, "BDD.md")
        print(f"Creating BDD documentation at {bdd_path}")
        with open(bdd_path, "w", encoding="utf-8") as f:
            f.write(bdd)
            
    # Generate VS Code Workspace
    workspace_file = os.path.join(workspace_dir, f"{ticket}.code-workspace")
    import json
    workspace_data = {
        "folders": [{"path": repo.get("name")} for repo in repositories],
        "settings": {}
    }
    with open(workspace_file, "w", encoding="utf-8") as f:
        json.dump(workspace_data, f, indent=2)
        
    print("\n=== Orchestration Complete! ===")
    print(f"Workspace located at: {workspace_dir}")
    print("Opening VS Code...")
    run_command(f'code "{workspace_file}"')

if __name__ == "__main__":
    main()
